version: 0.7.4-{build}
configuration:
- Release
- Debug
platform:
- Any CPU
os: Windows Server 2012 R2
install:
 - ps: |
     Add-Type -AssemblyName System.IO.Compression.FileSystem
            (new-object System.Net.WebClient).DownloadFile(
              'https://github.com/dokan-dev/dokany/releases/download/v0.7.4/DokanInstall_0.7.4.exe',
              'C:\projects\dokan-dotnet\DokanInstall.exe'
            )
 - cmd: C:\projects\dokan-dotnet\DokanInstall.exe /S
 
before_build:
  - nuget restore
build:
  project: DokanNet.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - reports@islog.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
